# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Docker build
      run: docker build . --file Dockerfile --tag demo_app
    
    - name: Docker run
      run: docker run -p 5000:5000 -d demo_app
    
    - name: Docker ps
      run: docker ps -a

    - name: Curl
      run: sleep 5; curl localhost:5000 
      
    # Runs a single command using the runners shell
    - name: Run yandex-tank -c test/load.yaml
      run: yandex-tank --version

